from __future__ import annotations


FINDING_CATEGORY_MAP: dict[str, list[str]] = {
    "email": ["pii"],
    "phone_number": ["pii"],
    "gdpr_full_name": ["pii"],
    "gdpr_email_address": ["pii"],
    "gdpr_phone_number": ["pii"],
    "gdpr_postal_address": ["pii"],
    "gdpr_birth_details": ["pii"],
    "gdpr_fin_pin": ["pii", "government_ids"],
    "gdpr_national_id": ["pii", "government_ids"],
    "gdpr_passport_number": ["pii", "government_ids"],
    "gdpr_signature": ["biometric_data", "pii"],
    "gdpr_photo_face_image": ["biometric_data", "pii"],
    "gdpr_vehicle_identifier": ["pii"],
    "gdpr_account_recovery_secret": ["pii", "identity_access", "credentials_secrets"],
    "gdpr_emergency_contact": ["pii"],
    "gdpr_ip_identifier": ["online_identifiers", "pii"],
    "gdpr_cookie_device_identifier": ["online_identifiers", "pii"],
    "gdpr_device_hardware_identifier": ["device_identifiers", "online_identifiers", "pii"],
    "gdpr_geolocation": ["location_data", "pii"],
    "gdpr_browsing_history": ["behavioral_data", "online_identifiers", "pii"],
    "gdpr_account_username": ["online_identifiers", "pii"],
    "gdpr_health_medical_record": ["phi", "pii"],
    "gdpr_mental_health_substance_use": ["phi", "pii"],
    "gdpr_disability_status": ["phi", "pii"],
    "gdpr_biometric_special_category": ["biometric_data", "pii"],
    "gdpr_genetic_dna_data": ["genetic_data", "special_category_context", "pii"],
    "gdpr_race_ethnicity": ["special_category_context", "pii"],
    "gdpr_religious_philosophical_belief": ["special_category_context", "pii"],
    "gdpr_political_affiliation": ["special_category_context", "pii"],
    "gdpr_sexual_orientation_sex_life": ["special_category_context", "phi", "pii"],
    "gdpr_trade_union_membership": ["special_category_context", "pii"],
    "gdpr_immigration_citizenship_status": ["government_ids", "pii"],
    "gdpr_criminal_record_background_check": ["special_category_context", "government_ids", "pii"],
    "gdpr_payment_card_data": ["pci_payment", "financial_records", "pii"],
    "gdpr_bank_account_data": ["financial_records", "pii"],
    "gdpr_tax_record": ["financial_records", "government_ids", "pii"],
    "gdpr_salary_compensation": ["hr_documents", "financial_records", "pii"],
    "gdpr_credit_score_report": ["financial_records", "pii"],
    "gdpr_invoice_billing_transaction_log": ["financial_records", "customer_data", "pii"],
    "gdpr_prerelease_financial_statement": ["financial_records", "confidential_business"],
    "gdpr_pricing_margin_forecast": ["financial_records", "confidential_business"],
    "gdpr_password_secret": ["credentials_secrets", "identity_access"],
    "gdpr_api_token_oauth_secret": ["credentials_secrets", "identity_access"],
    "gdpr_private_key_certificate_secret": ["credentials_secrets", "security_operations"],
    "gdpr_database_connection_string": ["credentials_secrets", "identity_access"],
    "gdpr_encryption_key_material": ["credentials_secrets", "security_operations"],
    "gdpr_session_token_jwt": ["credentials_secrets", "identity_access"],
    "gdpr_mfa_seed_recovery_code": ["credentials_secrets", "identity_access"],
    "gdpr_hr_employee_file": ["hr_documents", "pii"],
    "gdpr_benefits_insurance_enrollment": ["hr_documents", "financial_records", "phi", "pii"],
    "gdpr_background_check_drug_test": ["hr_documents", "government_ids", "phi", "pii"],
    "gdpr_timesheet_attendance": ["hr_documents", "pii"],
    "gdpr_org_chart_directory": ["hr_documents", "pii"],
    "gdpr_termination_layoff_plan": ["hr_documents", "pii"],
    "gdpr_source_code_algorithm": ["source_code", "intellectual_property", "confidential_business"],
    "gdpr_trade_secret_design": ["intellectual_property", "confidential_business"],
    "gdpr_patent_pending_unfiled": ["intellectual_property", "confidential_business"],
    "gdpr_ma_due_diligence": ["confidential_business", "financial_records", "legal_documents"],
    "gdpr_board_materials_minutes": ["confidential_business", "legal_documents"],
    "gdpr_strategy_roadmap_plan": ["confidential_business", "intellectual_property"],
    "gdpr_contract_nda_legal": ["legal_documents", "contracts", "confidential_business"],
    "gdpr_litigation_privileged_legal": ["legal_documents", "confidential_business"],
    "gdpr_vendor_supplier_terms": ["confidential_business", "contracts"],
    "gdpr_network_architecture_diagram": ["security_operations", "source_code", "confidential_business"],
    "gdpr_vulnerability_pentest_report": ["security_operations", "audit_accounting"],
    "gdpr_security_config_firewall_rule": ["security_operations", "confidential_business"],
    "gdpr_incident_access_audit_log": ["security_operations", "audit_accounting", "pii"],
    "gdpr_disaster_recovery_bcp_plan": ["security_operations", "confidential_business"],
    "gdpr_physical_security_badge_cctv": ["security_operations", "physical_security", "pii"],
    "employee_id": ["pii", "hr_documents"],
    "passport_number": ["pii", "government_ids"],
    "national_id": ["pii", "government_ids"],
    "ssn": ["pii", "government_ids"],
    "azerbaijan_fin": ["pii", "government_ids"],
    "credit_card": ["pci_payment"],
    "stripe_key": ["pci_payment", "credentials_secrets"],
    "iban": ["financial_records"],
    "swift_bic": ["financial_records"],
    "routing_account": ["financial_records"],
    "phi_context": ["phi"],
    "medical_record_context": ["phi"],
    "insurance_id_context": ["phi"],
    "special_category_context": ["biometric_data", "pii"],
    "biometric_context": ["biometric_data"],
    "payroll_context": ["hr_documents", "financial_records"],
    "salary_context": ["hr_documents", "financial_records"],
    "customer_context": ["customer_data", "pii"],
    "legal_contract_context": ["legal_documents", "contracts"],
    "privileged_legal_context": ["legal_documents"],
    "nda_context": ["legal_documents", "contracts"],
    "board_context": ["confidential_business", "intellectual_property"],
    "confidential_keyword": ["confidential_business"],
    "security_ops_context": ["security_operations", "audit_accounting"],
    "retention_policy_context": ["audit_accounting"],
    "repo_archive_context": ["source_code", "intellectual_property"],
    "build_log_context": ["source_code", "security_operations"],
    "source_code_secret_context": ["source_code", "credentials_secrets"],
    "private_key": ["credentials_secrets"],
    "certificate_private_key": ["credentials_secrets"],
    "p12_pfx_keystore": ["credentials_secrets"],
    "ssh_private_key": ["credentials_secrets"],
    "aws_access_key": ["credentials_secrets"],
    "aws_secret_key": ["credentials_secrets"],
    "azure_storage_key": ["credentials_secrets"],
    "azure_sas_token": ["credentials_secrets"],
    "google_api_key": ["credentials_secrets"],
    "gcp_service_account": ["credentials_secrets"],
    "github_token": ["credentials_secrets", "source_code"],
    "gitlab_token": ["credentials_secrets", "source_code"],
    "npm_token": ["credentials_secrets", "source_code"],
    "slack_token": ["credentials_secrets"],
    "sendgrid_key": ["credentials_secrets"],
    "twilio_key": ["credentials_secrets"],
    "datadog_key": ["credentials_secrets", "security_operations"],
    "sentry_dsn": ["credentials_secrets", "security_operations"],
    "pagerduty_key": ["credentials_secrets", "security_operations"],
    "splunk_token": ["credentials_secrets", "security_operations"],
    "newrelic_key": ["credentials_secrets", "security_operations"],
    "okta_token": ["credentials_secrets", "identity_access"],
    "auth0_secret": ["credentials_secrets", "identity_access"],
    "oauth_client_secret": ["credentials_secrets", "identity_access"],
    "bearer_token": ["credentials_secrets"],
    "password": ["credentials_secrets"],
    "api_key": ["credentials_secrets"],
    "connection_string": ["credentials_secrets"],
    "database_uri": ["credentials_secrets"],
    "jdbc_connection": ["credentials_secrets"],
    "basic_auth_url": ["credentials_secrets"],
    "docker_auth_config": ["credentials_secrets", "source_code"],
    "kubeconfig_secret": ["credentials_secrets", "security_operations"],
    "terraform_state_secret": ["credentials_secrets", "security_operations"],
    "saml_private_key": ["credentials_secrets", "identity_access"],
    "mfa_recovery_context": ["credentials_secrets", "identity_access"],
}


PATH_CATEGORY_KEYWORDS: tuple[tuple[str, list[str]], ...] = (
    ("health", ["phi"]),
    ("patient", ["phi"]),
    ("medical", ["phi"]),
    ("payment", ["pci_payment", "financial_records"]),
    ("cardholder", ["pci_payment"]),
    ("pci", ["pci_payment"]),
    ("finance", ["financial_records"]),
    ("invoice", ["financial_records", "customer_data"]),
    ("payroll", ["hr_documents", "financial_records"]),
    ("hr", ["hr_documents"]),
    ("employee", ["hr_documents", "pii"]),
    ("legal", ["legal_documents"]),
    ("contract", ["contracts", "legal_documents"]),
    ("customer", ["customer_data", "pii"]),
    ("client", ["customer_data", "pii"]),
    ("audit", ["audit_accounting"]),
    ("sox", ["audit_accounting", "financial_records"]),
    ("source", ["source_code"]),
    ("repo", ["source_code"]),
    ("secret", ["credentials_secrets"]),
    ("password", ["credentials_secrets"]),
    ("credential", ["credentials_secrets"]),
    ("identity", ["identity_access"]),
    ("okta", ["identity_access"]),
    ("confidential", ["confidential_business"]),
    ("board", ["confidential_business"]),
)


CRITICALITY_WEIGHTS = {
    "credentials_secrets": 25,
    "pci_payment": 25,
    "phi": 24,
    "biometric_data": 24,
    "government_ids": 22,
    "genetic_data": 24,
    "financial_records": 18,
    "identity_access": 18,
    "source_code": 16,
    "security_operations": 16,
    "hr_documents": 15,
    "customer_data": 14,
    "legal_documents": 14,
    "audit_accounting": 13,
    "confidential_business": 12,
    "intellectual_property": 12,
    "contracts": 10,
    "pii": 10,
    "online_identifiers": 10,
    "device_identifiers": 12,
    "location_data": 16,
    "behavioral_data": 14,
}
